[tox]
requires = tox-uv>=1
envlist = csslint,eslint,quality,py{311,312}-django{42,52},translations_validate

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
commands =
    coverage run manage.py test freetextresponse.tests
    coverage report
    coverage html

[testenv:clean]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    coverage erase
skip_install = True

[testenv:csslint]
allowlist_externals = {toxinidir}/node_modules/csslint/dist/cli.js
commands =
    {toxinidir}/node_modules/csslint/dist/cli.js src/freetextresponse/public/
dependency_groups = []
skip_install = True

[testenv:eslint]
allowlist_externals = {toxinidir}/node_modules/eslint/bin/eslint.js
commands =
    {toxinidir}/node_modules/eslint/bin/eslint.js --fix src/freetextresponse/public/view.js
dependency_groups = []
skip_install = True

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups =
    quality
commands =
    pycodestyle src/freetextresponse/
    pylint src/freetextresponse/

[testenv:translations_validate]
runner = uv-venv-lock-runner
allowlist_externals = make
dependency_groups =
    test
commands =
    make translations_validate

[testenv:translations_compile]
runner = uv-venv-lock-runner
dependency_groups =
    test
changedir = {toxinidir}/src/freetextresponse
commands =
    i18n_tool generate

[testenv:translations_dummy]
runner = uv-venv-lock-runner
dependency_groups =
    test
changedir = {toxinidir}/src/freetextresponse
commands =
    i18n_tool dummy

[testenv:translations_detect_changed]
runner = uv-venv-lock-runner
dependency_groups =
    test
changedir = {toxinidir}/src/freetextresponse
commands =
    i18n_tool extract
    i18n_tool changed

[testenv:translations_extract]
runner = uv-venv-lock-runner
dependency_groups =
    test
changedir = {toxinidir}/src/freetextresponse
commands =
    i18n_tool extract
